### ISSUE TITLE
Specified Python version needed

### ISSUE THREAD

**Issue by YuantingMaSC** [MaitreChen/MedGAN-ResLite#1]
may i know the specific python version of this work please

**Comment by MaitreChen** [comment]
Of course, the python version is 3.8.10, and pytorch is 1.10.0、cuda11.3

**Comment by MaitreChen** [comment]
By the way, the torch and cuda versions described in "requirement.txt" are used in the training phase. But the ones I described above are used in the reasoning phase, and both versions work fine
