### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by MaitreChen** [MaitreChen/MedGAN-ResLite#2]
Modify **setup_logging()** in project_dir/utils/setup.py:

file_name = f'log_{log_filename}_{current_time}.txt'   ---> file_name = f'{log_filename}_{current_time}.txt'

**Comment by Z3731730** [comment]
In addition to the pneumoniamnist dataset, this project also provide synthetic data generated using DCGAN. fake文件如何划分train、val、test

**Comment by MaitreChen** [comment]
val和test是空的，只对train操作，使得normal和pneumonia的样本数量一致。

**Comment by Z3731730** [comment]
您好，我想问一下为什么测试集中肺炎数据有390张图片，最后只使用了376张



---Original---
From: "Hongbin ***@***.***&gt;
Date: Fri, Nov 22, 2024 21:00 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [MaitreChen/MedGAN-ResLite] FileNotFoundError (Issue #2)




 
val和test是空的，只对train操作，使得normal和pneumonia的样本数量一致。

**Comment by MaitreChen** [comment]
这是MedGAN-ResLite-V1中的一个问题，可以看看MedGAN-ResLite-V2：https://github.com/MaitreChen/MedGAN-ResLite/tree/v2-fix
